// Auto-generated by tools/goertzel_coeffgen.py
localparam integer GOERTZEL_N_BLOCK = 1000;
localparam integer GOERTZEL_Q_SHIFT = 17;
localparam signed [17:0] GOERTZEL_COEFF_2COS_Q17 = 18'sd16460;
localparam signed [17:0] GOERTZEL_COS_Q17        = 18'sd8230;
localparam signed [17:0] GOERTZEL_SIN_Q17        = 18'sd130813;
