#!/usr/bin/env python3
"""
Generate fixed-point Goertzel coefficients and metadata.

Outputs:
- JSON metadata
- Verilog header (.vh)
- Markdown summary
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path


def qround(x: float, q_shift: int) -> int:
    return int(round(x * (1 << q_shift)))


def generate(fs_hz: float, target_hz: float, n_block: int, q_shift: int) -> dict:
    omega = 2.0 * math.pi * target_hz / fs_hz
    k_exact = n_block * target_hz / fs_hz
    k_nearest = int(round(k_exact))
    coherent = abs(k_exact - k_nearest) < 1e-12

    coeff_2cos = qround(2.0 * math.cos(omega), q_shift)
    coeff_cos = qround(math.cos(omega), q_shift)
    coeff_sin = qround(math.sin(omega), q_shift)

    width_hint = max(abs(coeff_2cos), abs(coeff_cos), abs(coeff_sin)).bit_length() + 1

    return {
        "fs_hz": fs_hz,
        "target_hz": target_hz,
        "n_block": n_block,
        "k_exact": k_exact,
        "k_nearest": k_nearest,
        "coherent": coherent,
        "omega_rad_per_sample": omega,
        "q_shift": q_shift,
        "q_format": f"Q{q_shift}",
        "coeff_2cos_q": coeff_2cos,
        "cos_q": coeff_cos,
        "sin_q": coeff_sin,
        "coefficient_width_hint_bits": width_hint,
        "scale": 1 << q_shift,
    }


def write_outputs(meta: dict, out_dir: Path, name: str) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    json_path = out_dir / f"{name}.json"
    vh_path = out_dir / f"{name}.vh"
    md_path = out_dir / f"{name}.md"

    with json_path.open("w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2)
        f.write("\n")

    with vh_path.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by tools/goertzel_coeffgen.py\n")
        f.write(f"localparam integer GOERTZEL_N_BLOCK = {meta['n_block']};\n")
        f.write(f"localparam integer GOERTZEL_Q_SHIFT = {meta['q_shift']};\n")
        f.write(f"localparam signed [17:0] GOERTZEL_COEFF_2COS_Q17 = 18'sd{meta['coeff_2cos_q']};\n")
        f.write(f"localparam signed [17:0] GOERTZEL_COS_Q17        = 18'sd{meta['cos_q']};\n")
        f.write(f"localparam signed [17:0] GOERTZEL_SIN_Q17        = 18'sd{meta['sin_q']};\n")

    with md_path.open("w", encoding="utf-8") as f:
        f.write(f"# Goertzel Coefficients: {name}\n\n")
        f.write(f"- fs: `{meta['fs_hz']}` Hz\n")
        f.write(f"- target: `{meta['target_hz']}` Hz\n")
        f.write(f"- N block: `{meta['n_block']}`\n")
        f.write(f"- k exact: `{meta['k_exact']}`\n")
        f.write(f"- coherent: `{meta['coherent']}`\n")
        f.write(f"- q format: `{meta['q_format']}`\n")
        f.write(f"- 2cos coeff: `{meta['coeff_2cos_q']}`\n")
        f.write(f"- cos coeff: `{meta['cos_q']}`\n")
        f.write(f"- sin coeff: `{meta['sin_q']}`\n")

    print(f"Wrote {json_path}")
    print(f"Wrote {vh_path}")
    print(f"Wrote {md_path}")


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--fs", type=float, required=True)
    p.add_argument("--freq", type=float, required=True)
    p.add_argument("--n-block", type=int, default=1000)
    p.add_argument("--q-shift", type=int, default=17)
    p.add_argument("--out-dir", type=Path, default=Path("coeffs"))
    p.add_argument("--name", type=str, default=None)
    args = p.parse_args()

    meta = generate(args.fs, args.freq, args.n_block, args.q_shift)
    name = args.name or f"goertzel_{args.freq/1e6:.3f}MHz_N{args.n_block}_Q{args.q_shift}".replace(".", "p")
    write_outputs(meta, args.out_dir, name)

    if not meta["coherent"]:
        print("WARNING: target is not coherent with fs/N. Use generalized Goertzel or expect leakage.")


if __name__ == "__main__":
    main()
